config/routes.rb
Rails.application.routes.draw do

  get 'new/show'

  devise_for :users

  resources :users do
    resources :items, only: [:new, :create, :destroy, :index]
  end

  get 'welcome/about'
  get 'welcome/index'

  root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :name, length: { minimum: 5, maximum: 300 }, presence: true
  default_scope { order('updated_at DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :wikis, through: :collaborators
  has_many :items


  before_save {
    self.email = email.downcase
    #convert name to a string
    temp = name.to_s
    #split name into words and then capitalize but only if a space exists
    self.name = temp.split(' ').map(&:capitalize).join(' ') if temp.match(/.\s./)
  }


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }, if: "encrypted_password.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 100 },
             format: { with: EMAIL_REGEX }


# if self role is not defined then default to a member role
  #before_save {self.role ||= :standard }
  after_initialize {self.role ||= :standard}

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  #attr_accessible :email, :password, :name, :password_confirmation
  enum role: [:standard, :premium, :admin]


end

app/controllers/application_controller.rb
include ApplicationHelper

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


before_filter :configure_permitted_parameters, if: :devise_controller?
before_action :authenticate_user!, except: [:index, :show]



     protected

     	def configure_permitted_parameters
        	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation ) }
        	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }

     	end


     private

    	def user_not_authorized
    		flash[:alert] = "You are not authorized to perform this action."
    		redirect_to(root_path)
  		end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
      @items = Item.where(user_id: params[:user_id])
      authorize @items
      @item = Item.new
      authorize @item

  end

  def new
      @item = Item.new
      authorize @item
  end

  def create
      @item = Item.new(item_params)
      @item.user_id = current_user.id
      @user = User.find(current_user.id)
      @new_item = Item.new
      authorize @item
      if !@item.save
        flash.now[:alert] = "There was an error saving the item. Please try again."
        #render :new
      end

  end

  def destroy
      @item = Item.find(params[:id])
      authorize @item
      if !@item.destroy
        flash.now[:alert] = "There was an error deleting the item."
        redirect_to user_items_path
      end
  end

    respond_to do |format|
         format.html
         format.js
    end

  private

    def item_params
      params.require(:item).permit(:name, :user_id)
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    redirect_to (welcome_index_path) if current_user.blank?
    @user = current_user
    @items = Item.where(user_id: params[:id])

  end

  def new
  	end

  #### end class
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_group_tag(errors, &block)

      if errors.any?
        content_tag :div, capture(&block), class: 'form-group has-error'
      else
        content_tag :div, capture(&block), class: 'form-group'
      end

    end

    def markdown(text)
        options = {
          filter_html:     true,
          hard_wrap:       true,
          link_attributes: { rel: 'nofollow', target: "_blank" },
          space_after_headers: true,
          fenced_code_blocks: true
        }

        extensions = {
          autolink:           true,
          superscript:        true,
          disable_indented_code_blocks: true
        }

        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)

        markdown.render(text).html_safe
      end
  

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
  <%# f.label :add %>
  <%# f.text_field :name, class: 'form-control', placeholder: "Enter to-do description" %>

<div class="js-new-item">
  <%= form_for item, url: user_items_path, remote: true do |f| %>
    <%= f.label :add %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter to-do description" %>
    <br>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    <br>
  <% end %>
</div>

app/views/items/_item.html.erb
<tr class="js-a-item-<%=item.id=%>">
  <td>
    <%= item.name %></br>
  </td>

  <td>

    <%= distance_of_time_in_words(Time.now - 7.days, item.created_at)   %>
  </td>

  <td>
    <%= link_to "", user_item_path(item.user_id, item.id), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
    <%# link_to "", show_items_path, method: :delete, class: 'glyphicon glyphicon-ok' %>
  </td>
</tr>

app/views/items/create.js.erb
<% if @item.valid? %>

   $('.js-items').prepend("<%= escape_javascript(render partial: 'items/item', locals: {item: @item})%>");
   $('.js-new-item').html("<%= escape_javascript(render partial: 'items/form', locals: {item: @new_item})%>");

 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
 <% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
   $('.js-a-item-<%=@item.id=%>').hide()
 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
 <% end %>

app/views/items/index.html.erb
<% if @item.errors.any? %>

      <div class="alert alert-danger">

        <h4><%= pluralize(@item.errors.count, "error") %>.</h4>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
      </div>

<% end %>


 <div class="row">
     <div class="col-md-12">
         <h3>Your To-Do List</h3>
         <table class="table table-bordered table-striped">
           <thead>
             <tr>
               <th>Description</th>
               <th>Days left</th>
               <th>Complete</th>
             </tr>
           </thead>
           <tbody class="js-items">
                <% @items.each do |item| %>
                      <%= render partial: 'items/item', locals: {item: item} %>
                <% end %>
          </tbody>
        </table>
     </div>
<%# if policy(@items).new? %>

<div class="row">
    <div class="col-md-8">
      <%= render partial: 'items/form', locals: {item: @item} %>
    </div>
</div>

<br>

app/views/items/new.html.erb
<% if @item.errors.any? %>

      <div class="alert alert-danger">

        <h4><%= pluralize(@item.errors.count, "error") %>.</h4>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
      </div>

<% end %>


<h1>New To-Do item</h1>

<br>
<div class="row">

  <div class="col-md-8">
    <%= form_for @item, url: user_items_path do |f| %>
      <div class="form-group">
        <%= render partial: 'items/form', locals: {f: f} %>
      </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
      <br>
      <br>

    <% end %>
  </div>

  <div class="col-md-4">
    <br>
    <p> > Your chance to give yourself some work</p>

  </div>




</div>

app/views/items/show.html.erb
<% if @item.errors.any? %>

      <div class="alert alert-danger">

        <h4><%= pluralize(@item.errors.count, "error") %>.</h4>
        <ul>
          <% @item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
      </div>

<% end %>


 <div class="row">
     <div class="col-md-12">
         <h3>Your To-Do List</h3>
         <table class="table table-bordered table-striped">
           <thead>
             <tr>
               <th>Description</th>
               <th>Days left</th>
               <th>Complete</th>
             </tr>
           </thead>
           <tbody>
             <% @items.each do |item| %>
               <tr>
                 <%= render partial: 'items/item', locals: {item: item} %>
               </tr>
             <% end %>
          </tbody>
        </table>
     </div>
<%# if policy(@items).new? %>

<div class="row">
    <div class="col-md-8">

  <%= form_for @item, url: user_items_path do |f| %>
      <%= render partial: 'items/form', locals: {f: f} %>
      <br>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    <br>
  <% end %>

  <br>
  <%# link_to "New To-Do", new_user_item_path(user_id:current_user.id), class: 'btn btn-success' %>
  <br>
  <br>
<%# end %>
<br>

</div<

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlocItOff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="navbar navbar-inverse" style="background-color:##3C3E54;"">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><%= link_to "BlocItOff", welcome_index_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "To Do List", user_items_path(current_user) %></li>
        <% end %>
        <li><%= link_to "About", "#" %></li>
      </ul>


      <ul span class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
          <li><%= image_tag current_user.avatar_url(40), class: "gravatar" %></li>
          <li><%= link_to current_user.email, current_user %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>


    </div>
  </nav>

    <div class="flash">
      <% if flash[:notice] %>
        <br>
        <br>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <br>
        <br>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
      <% elsif flash[:alert] %>
        <br>
        <br>
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
        </div>
     <% end %>
   </div>

<div class="container">
    <%= yield %>
</div>


</body>
</html>

app/views/users/show.html.erb
<h1>User Profile</h1>
<hr>

<div class="row">
   <div class="col-md-2">
     <br />
     <% avatar_url = @user.avatar_url(138) %>
     <% if avatar_url %>
       <div class="media-left">
         <%= image_tag avatar_url, class: 'media-object' %>
       </div>
     <% end %>
   </div>


     <div class="col-md-10">
       <h3 class="media-heading"><%= @user.name %></h3>
       <% if @user.premium? || @user.admin? %>
         <span style="color:red"><%= @user.role.capitalize %></span>
       <% else %>
         <span style="color:green"><%= @user.role.capitalize %></span>
       <% end %>
       account type<br>
       <p><span style="font-weight:bold;">Email: </span><%= @user.email %><br>
       <span style="font-weight:bold;">Last signed in: </span><%= @user.last_sign_in_at %><br>
       <span style="font-weight:bold;">Member since: </span><%= @user.created_at %></p>
       <p><span style="font-weight:bold;">Number of to-do items: </span><%= 300 %><br></p>
     </div>

 </div>
 <br>

 <%= link_to "Edit Registration", edit_user_registration_path, class: 'btn btn-primary' %>

<br>

 <div class="row">
     <div class="col-md-12">
         <h3>Your To-Do List</h3>
         <table class="table table-bordered table-striped">
           <thead>
             <tr>
               <th>Description</th>
               <th>Days left</th>
               <th>Complete</th>
             </tr>
           </thead>
           <tbody class="js-items">
                <% @items.each do |item| %>
                      <%= render partial: 'items/item', locals: {item: item} %>
                <% end %>
          </tbody>
        </table>
     </div>

 </div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron banner-image" style="color:white; background-color:brown">
     <h1>BlocItOff: Your task manager</h1>
     <p>World's best self-destructing to-do lists!</p>

     <% if !current_user %>
       <div class="col-md-12">
         <div id="sign-up" style = "color:white;">
           <h4>Create your to-do lists today!</h4>
           <%= link_to "Sign In", new_user_session_path %> or
           <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
         </div>
       </div>
     <% end %>
  </div>


   <div class="row text-center">
     <h2>Get Organized Today</h2>
     <p>BloccItOff will make your life super fantastic with all your peers asking how do you stay so organized</p>
     <p>The very best part is that it is absoultely free!
  </div>

</div>